# Project : Multiple Disease Prediction

In [ ]:
# Step 1 : Import Library
import pandas as pd

In [ ]:
# Step 2 : Read Dataset
df=pd.read_csv('https://github.com/YBIFoundation/Dataset/raw/main/MultipleDiseasePrediction.csv')

In [ ]:
df.head()

,itching,skin_rash,nodal_skin_eruptions,continuous_sneezing,shivering,chills,joint_pain,stomach_pain,acidity,ulcers_on_tongue,...,blackheads,scurring,skin_peeling,silver_like_dusting,small_dents_in_nails,inflammatory_nails,blister,red_sore_around_nose,yellow_crust_ooze,prognosis
0,1,1,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,Fungal infection
1,0,1,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,Fungal infection
2,1,0,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,Fungal infection
3,1,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,Fungal infection
4,1,1,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,Fungal infection

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4920 entries, 0 to 4919
Columns: 133 entries, itching to prognosis
dtypes: int64(132), object(1)
memory usage: 5.0+ MB

In [ ]:
df.describe()

,itching,skin_rash,nodal_skin_eruptions,continuous_sneezing,shivering,chills,joint_pain,stomach_pain,acidity,ulcers_on_tongue,...,pus_filled_pimples,blackheads,scurring,skin_peeling,silver_like_dusting,small_dents_in_nails,inflammatory_nails,blister,red_sore_around_nose,yellow_crust_ooze
count,4920.000000,4920.000000,4920.000000,4920.000000,4920.000000,4920.000000,4920.000000,4920.000000,4920.000000,4920.000000,...,4920.000000,4920.000000,4920.000000,4920.000000,4920.000000,4920.000000,4920.000000,4920.000000,4920.000000,4920.000000
mean,0.137805,0.159756,0.021951,0.045122,0.021951,0.162195,0.139024,0.045122,0.045122,0.021951,...,0.021951,0.021951,0.021951,0.023171,0.023171,0.023171,0.023171,0.023171,0.023171,0.023171
std,0.344730,0.366417,0.146539,0.207593,0.146539,0.368667,0.346007,0.207593,0.207593,0.146539,...,0.146539,0.146539,0.146539,0.150461,0.150461,0.150461,0.150461,0.150461,0.150461,0.150461
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
75%,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
max,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,...,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000

In [ ]:
df.columns

Index(['itching', 'skin_rash', 'nodal_skin_eruptions', 'continuous_sneezing',
       'shivering', 'chills', 'joint_pain', 'stomach_pain', 'acidity',
       'ulcers_on_tongue',
       ...
       'blackheads', 'scurring', 'skin_peeling', 'silver_like_dusting',
       'small_dents_in_nails', 'inflammatory_nails', 'blister',
       'red_sore_around_nose', 'yellow_crust_ooze', 'prognosis'],
      dtype='object', length=133)

In [ ]:
# Step 3 : Define your Problem(X and y)
X=df.drop(['prognosis'],axis=1)
y=df['prognosis']

In [ ]:
X

,itching,skin_rash,nodal_skin_eruptions,continuous_sneezing,shivering,chills,joint_pain,stomach_pain,acidity,ulcers_on_tongue,...,pus_filled_pimples,blackheads,scurring,skin_peeling,silver_like_dusting,small_dents_in_nails,inflammatory_nails,blister,red_sore_around_nose,yellow_crust_ooze
0,1,1,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,1,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,1,0,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,1,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,1,1,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4915,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4916,0,1,0,0,0,0,0,0,0,0,...,1,1,1,0,0,0,0,0,0,0
4917,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4918,0,1,0,0,0,0,1,0,0,0,...,0,0,0,1,1,1,1,0,0,0
4919,0,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,1,1,1

In [ ]:
y

0                              Fungal infection
1                              Fungal infection
2                              Fungal infection
3                              Fungal infection
4                              Fungal infection
                         ...
4915    (vertigo) Paroymsal  Positional Vertigo
4916                                       Acne
4917                    Urinary tract infection
4918                                  Psoriasis
4919                                   Impetigo
Name: prognosis, Length: 4920, dtype: object

In [ ]:
df.shape,X.shape,y.shape

((4920, 133), (4920, 132), (4920,))

In [ ]:
y.value_counts()

prognosis
Fungal infection                           120
Allergy                                    120
GERD                                       120
Chronic cholestasis                        120
Drug Reaction                              120
Peptic ulcer diseae                        120
AIDS                                       120
Diabetes                                   120
Gastroenteritis                            120
Bronchial Asthma                           120
Hypertension                               120
Migraine                                   120
Cervical spondylosis                       120
Paralysis (brain hemorrhage)               120
Jaundice                                   120
Malaria                                    120
Chicken pox                                120
Dengue                                     120
Typhoid                                    120
hepatitis A                                120
Hepatitis B                                120
Hepatitis C                                120
Hepatitis D                                120
Hepatitis E                                120
Alcoholic hepatitis                        120
Tuberculosis                               120
Common Cold                                120
Pneumonia                                  120
Dimorphic hemmorhoids(piles)               120
Heart attack                               120
Varicose veins                             120
Hypothyroidism                             120
Hyperthyroidism                            120
Hypoglycemia                               120
Osteoarthristis                            120
Arthritis                                  120
(vertigo) Paroymsal  Positional Vertigo    120
Acne                                       120
Urinary tract infection                    120
Psoriasis                                  120
Impetigo                                   120
Name: count, dtype: int64

In [ ]:
# Step 4: Train and Test split
from sklearn.model_selection import train_test_split

In [ ]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.25,stratify=y,random_state=2529)

In [ ]:
X_train

,itching,skin_rash,nodal_skin_eruptions,continuous_sneezing,shivering,chills,joint_pain,stomach_pain,acidity,ulcers_on_tongue,...,pus_filled_pimples,blackheads,scurring,skin_peeling,silver_like_dusting,small_dents_in_nails,inflammatory_nails,blister,red_sore_around_nose,yellow_crust_ooze
719,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
857,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1009,0,0,0,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4584,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1066,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4036,0,0,0,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1543,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
226,0,0,0,0,0,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4603,0,0,0,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
335,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [ ]:
X_test

,itching,skin_rash,nodal_skin_eruptions,continuous_sneezing,shivering,chills,joint_pain,stomach_pain,acidity,ulcers_on_tongue,...,pus_filled_pimples,blackheads,scurring,skin_peeling,silver_like_dusting,small_dents_in_nails,inflammatory_nails,blister,red_sore_around_nose,yellow_crust_ooze
1134,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2387,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3755,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2440,0,1,0,0,0,0,1,0,0,0,...,0,0,0,1,1,1,1,0,0,0
412,1,0,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2474,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
21,0,0,0,0,0,0,0,1,0,1,...,0,0,0,0,0,0,0,0,0,0
162,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1057,0,0,0,0,0,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
996,0,1,0,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [ ]:
y_test

1134         Hypothyroidism
2387           Hypoglycemia
3755    Alcoholic hepatitis
2440              Psoriasis
412        Fungal infection
               ...
2474               Jaundice
21                     GERD
162             Chicken pox
1057            Hepatitis E
996                  Dengue
Name: prognosis, Length: 1230, dtype: object

In [ ]:
y_train

719          Varicose veins
857     Chronic cholestasis
1009                Typhoid
4584           Hypoglycemia
1066    Alcoholic hepatitis
               ...
4036                Typhoid
1543         Hypothyroidism
226             Hepatitis D
4603               Migraine
335            Hypoglycemia
Name: prognosis, Length: 3690, dtype: object

In [ ]:
X_train.shape,X_test.shape,y_train.shape,y_test.shape

((3690, 132), (1230, 132), (3690,), (1230,))

In [ ]:
# Step 5: Select Model
from sklearn.linear_model import LogisticRegression

In [ ]:
model=LogisticRegression()

In [ ]:
# Step 6: Train Model
model.fit(X_train,y_train)

LogisticRegression()

In [ ]:
model.intercept_

array([-0.00317891,  1.18294676,  1.07245688,  0.07210602,  1.27552621,
        0.68641973,  0.2425542 ,  0.66910112, -0.79473727, -0.55303103,
       -0.98082691, -1.34729995, -0.25391624,  0.83950788,  0.44302909,
        1.03718135,  0.17192255,  1.01485848,  0.93441301, -0.75596473,
        0.31916768, -1.12964267, -1.34751031,  0.5092304 , -0.48775506,
       -0.85300105, -0.48696716,  0.55699832, -0.66971809, -0.57301202,
       -0.1206785 ,  0.38082763,  0.93557348,  0.27826461, -0.66673416,
        0.35641808, -1.40823257, -1.03671727,  1.21108841,  0.27112432,
       -0.99179229])

In [ ]:
model.coef_

array([[-0.17475102, -0.18880058, -0.02944051, ..., -0.02266744,
        -0.02217999, -0.02266744],
       [-0.26497842, -0.50349827, -0.06380326, ..., -0.19755455,
        -0.19114904, -0.19755455],
       [-0.51449794,  1.49155626, -0.23048802, ..., -0.20978548,
        -0.20435699, -0.20978548],
       ...,
       [-0.34146146, -0.45490108, -0.06599446, ..., -0.05688753,
        -0.05558933, -0.05688753],
       [-0.14896404, -0.20362935, -0.03729636, ..., -0.03048999,
        -0.02979668, -0.03048999],
       [-0.27805425, -0.11575178, -0.01280721, ..., -0.01113207,
        -0.01090379, -0.01113207]])

In [ ]:
# Step 7 : Prediction
y_pred=model.predict(X_test)

In [ ]:
y_pred

array(['Hypothyroidism', 'Hypoglycemia', 'Alcoholic hepatitis', ...,
       'Chicken pox', 'Hepatitis E', 'Dengue'], dtype=object)

In [ ]:
model.predict_proba(X_test)

array([[1.15016854e-04, 3.49986868e-04, 3.88649110e-04, ...,
        4.29517184e-04, 5.43958052e-04, 4.32748060e-05],
       [4.84424179e-04, 1.34601244e-04, 1.92981762e-04, ...,
        1.99272062e-04, 2.92369668e-04, 6.79199881e-05],
       [2.09375589e-04, 1.86049865e-04, 2.16080024e-04, ...,
        2.23077661e-04, 1.15117321e-04, 2.57863333e-04],
       ...,
       [1.95464404e-04, 8.34888491e-04, 1.15445873e-04, ...,
        2.06778412e-04, 3.28993213e-04, 1.86459909e-04],
       [1.51387115e-04, 2.12818865e-04, 4.25182777e-05, ...,
        5.54577933e-05, 9.43385589e-05, 8.65690668e-04],
       [8.26691539e-04, 1.97935023e-04, 3.70862207e-04, ...,
        7.16425979e-05, 1.71406324e-04, 2.83611047e-04]])

In [ ]:
# Step 8: Evaluation
from sklearn.metrics import classification_report

In [ ]:
print(classification_report(y_test,y_pred))

                                         precision    recall  f1-score   support

(vertigo) Paroymsal  Positional Vertigo       1.00      1.00      1.00        30
                                   AIDS       1.00      1.00      1.00        30
                                   Acne       1.00      1.00      1.00        30
                    Alcoholic hepatitis       1.00      1.00      1.00        30
                                Allergy       1.00      1.00      1.00        30
                              Arthritis       1.00      1.00      1.00        30
                       Bronchial Asthma       1.00      1.00      1.00        30
                   Cervical spondylosis       1.00      1.00      1.00        30
                            Chicken pox       1.00      1.00      1.00        30
                    Chronic cholestasis       1.00      1.00      1.00        30
                            Common Cold       1.00      1.00      1.00        30
                                 Dengue       1.00      1.00      1.00        30
                              Diabetes        1.00      1.00      1.00        30
           Dimorphic hemmorhoids(piles)       1.00      1.00      1.00        30
                          Drug Reaction       1.00      1.00      1.00        30
                       Fungal infection       1.00      1.00      1.00        30
                                   GERD       1.00      1.00      1.00        30
                        Gastroenteritis       1.00      1.00      1.00        30
                           Heart attack       1.00      1.00      1.00        30
                            Hepatitis B       1.00      1.00      1.00        30
                            Hepatitis C       1.00      1.00      1.00        30
                            Hepatitis D       1.00      1.00      1.00        30
                            Hepatitis E       1.00      1.00      1.00        30
                          Hypertension        1.00      1.00      1.00        30
                        Hyperthyroidism       1.00      1.00      1.00        30
                           Hypoglycemia       1.00      1.00      1.00        30
                         Hypothyroidism       1.00      1.00      1.00        30
                               Impetigo       1.00      1.00      1.00        30
                               Jaundice       1.00      1.00      1.00        30
                                Malaria       1.00      1.00      1.00        30
                               Migraine       1.00      1.00      1.00        30
                        Osteoarthristis       1.00      1.00      1.00        30
           Paralysis (brain hemorrhage)       1.00      1.00      1.00        30
                    Peptic ulcer diseae       1.00      1.00      1.00        30
                              Pneumonia       1.00      1.00      1.00        30
                              Psoriasis       1.00      1.00      1.00        30
                           Tuberculosis       1.00      1.00      1.00        30
                                Typhoid       1.00      1.00      1.00        30
                Urinary tract infection       1.00      1.00      1.00        30
                         Varicose veins       1.00      1.00      1.00        30
                            hepatitis A       1.00      1.00      1.00        30

                               accuracy                           1.00      1230
                              macro avg       1.00      1.00      1.00      1230
                           weighted avg       1.00      1.00      1.00      1230